version: "3"
services:
  db1:
    image: mysql:8.0
    container_name: "db_1"
    ports:
      - "33306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db1
  db2:
    image: mysql:8.0
    container_name: "db_2"
    ports:
      - "33307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db2